; Plenipo's installer, in plain words (Phase 13). Every message Tauri's installer shows in
; English; the owner's data is kept unless the owner chooses to delete it.
LangString addOrReinstall ${LANG_ENGLISH} "Install it again"
LangString alreadyInstalled ${LANG_ENGLISH} "Already installed"
LangString alreadyInstalledLong ${LANG_ENGLISH} "${PRODUCTNAME} ${VERSION} is already installed. Choose what to do, then click Next. Your data is kept."
LangString appRunning ${LANG_ENGLISH} "{{product_name}} is open. Quit it from the tray, then try again."
LangString appRunningOkKill ${LANG_ENGLISH} "{{product_name}} is open.$\nClick OK to close it. Work that is running stops."
LangString chooseMaintenanceOption ${LANG_ENGLISH} "Choose what to do."
LangString choowHowToInstall ${LANG_ENGLISH} "Choose how to install ${PRODUCTNAME}."
LangString createDesktop ${LANG_ENGLISH} "Put a shortcut on the desktop"
LangString dontUninstall ${LANG_ENGLISH} "Install over it (your data is kept)"
LangString dontUninstallDowngrade ${LANG_ENGLISH} "Install over it (going back to an older version is turned off for this installer)"
LangString failedToKillApp ${LANG_ENGLISH} "{{product_name}} could not be closed. Quit it from the tray, then try again."
LangString installingWebview2 ${LANG_ENGLISH} "Installing WebView2..."
LangString newerVersionInstalled ${LANG_ENGLISH} "A newer version of ${PRODUCTNAME} is installed. You can go back to this older version: your data is kept. If the newer version changed the Ledger, restore the backup it made from Diagnostics. Choose what to do, then click Next."
LangString older ${LANG_ENGLISH} "older"
LangString olderOrUnknownVersionInstalled ${LANG_ENGLISH} "An $R4 version of ${PRODUCTNAME} is installed. Choose how to update it, then click Next. Your data is kept either way, and Plenipo backs up the Ledger when the new version first starts."
LangString silentDowngrades ${LANG_ENGLISH} "This installer cannot go back to an older version silently. Run it without /S.$\n"
LangString unableToUninstall ${LANG_ENGLISH} "Plenipo could not be uninstalled."
LangString uninstallApp ${LANG_ENGLISH} "Uninstall ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_ENGLISH} "Uninstall it first, then install (your data is kept)"
LangString unknown ${LANG_ENGLISH} "unknown"
LangString webview2AbortError ${LANG_ENGLISH} "WebView2 could not be installed, and Plenipo needs it. Run the installer again."
LangString webview2DownloadError ${LANG_ENGLISH} "WebView2 could not be downloaded: $0"
LangString webview2DownloadSuccess ${LANG_ENGLISH} "WebView2 was downloaded"
LangString webview2Downloading ${LANG_ENGLISH} "Downloading WebView2..."
LangString webview2InstallError ${LANG_ENGLISH} "WebView2 did not install (code $1)"
LangString webview2InstallSuccess ${LANG_ENGLISH} "WebView2 was installed"
LangString deleteAppData ${LANG_ENGLISH} "Also delete my Plenipo data: the Ledger, its backups, settings, and saved secrets"
