-- Reverses 0004_workforce. Development/test use only (see ADR-006).
DROP INDEX sessions_by_agent;
DROP INDEX tasks_by_position;
DROP TABLE settings;
DROP TRIGGER oversight_is_kept;
DROP TRIGGER oversight_stays_ended;
DROP TRIGGER oversight_is_immutable;
DROP INDEX oversight_by_overseer;
DROP INDEX oversight_by_target;
DROP INDEX oversight_once;
DROP TABLE oversight;
DROP INDEX agents_one_incumbent;
DROP INDEX agents_one_per_task;
DROP INDEX agents_by_position;
ALTER TABLE agent_instances DROP COLUMN retired_at;
ALTER TABLE agent_instances DROP COLUMN task_id;
ALTER TABLE agent_instances DROP COLUMN model;
ALTER TABLE agent_instances DROP COLUMN runtime_id;
ALTER TABLE agent_instances DROP COLUMN position_id;
DROP INDEX projects_one_coordinator;
ALTER TABLE projects DROP COLUMN status;
ALTER TABLE projects DROP COLUMN capability_profile;
ALTER TABLE projects DROP COLUMN allowed_runtimes;
ALTER TABLE projects DROP COLUMN coordinator_position_id;
ALTER TABLE projects DROP COLUMN description;
DROP INDEX departments_one_head;
ALTER TABLE departments DROP COLUMN head_position_id;
DROP TRIGGER positions_are_kept;
DROP TRIGGER positions_stay_archived;
DROP TRIGGER positions_role_is_fixed;
DROP INDEX positions_unique_title;
DROP INDEX positions_by_supervisor;
DROP TABLE positions;
DROP TRIGGER roles_class_is_fixed;
