// Project work and objective result fixtures for tests (Phase 8).
import type { ObjectiveReport, ProjectWork, Workspace } from "@plenipo/types";

export const T0 = Date.UTC(2026, 8, 26, 15, 0, 0);

export const workingCopy = (patch: Partial<Workspace> = {}): Workspace => ({
  id: "ws-1",
  projectId: "pr-web",
  correlationId: "corr-1",
  rootTaskId: "task-obj-1",
  parentId: null,
  repository: "D:\\projects\\website",
  subfolder: "",
  path: "C:\\Users\\owner\\AppData\\Roaming\\Plenipo\\working-copies\\website-1",
  branch: "plenipo/add-a-contact-page-corr0001",
  baseRef: "main",
  baseCommit: "abc1234",
  state: "active",
  facts: {
    head: "def5678",
    commits: [{ hash: "def5678", subject: "Add the contact page" }],
    files: [{ path: "src/contact.html", added: 40, removed: 0, committed: true }],
    uncommitted: 1,
    pushed: false,
    checkedAt: T0 - 60_000,
  },
  createdAt: T0 - 20 * 60_000,
  updatedAt: T0 - 60_000,
  removedAt: null,
  ...patch,
});

export function sampleWork(patch: Partial<ProjectWork> = {}): ProjectWork {
  return {
    projectId: "pr-web",
    objectives: [
      {
        rootTaskId: "task-obj-1",
        objective: "Add a contact page\n\nThe form sends to the sales inbox.",
        positionTitle: "Engineering Manager",
        state: "running",
        createdAt: T0 - 20 * 60_000,
        completedAt: null,
        tasks: 5,
        active: 2,
        failed: 0,
        waitingApprovals: 1,
        branch: "plenipo/add-a-contact-page-corr0001",
        projectId: "pr-web",
        answer: null,
      },
      {
        rootTaskId: "task-obj-0",
        objective: "Fix the typo on the home page",
        positionTitle: "Website Supervisor",
        state: "succeeded",
        createdAt: T0 - 2 * 3_600_000,
        completedAt: T0 - 3_500_000,
        tasks: 2,
        active: 0,
        failed: 0,
        waitingApprovals: 0,
        branch: null,
        projectId: "pr-web",
        answer: "The typo is fixed.",
      },
    ],
    workingCopies: [workingCopy()],
    ...patch,
  };
}

export function sampleReport(patch: Partial<ObjectiveReport> = {}): ObjectiveReport {
  return {
    rootTaskId: "task-obj-1",
    correlationId: "corr-1",
    objective: "Add a contact page\n\nThe form sends to the sales inbox.",
    positionId: "p-eng",
    positionTitle: "Engineering Manager",
    projectId: "pr-web",
    projectName: "Website Relaunch",
    state: "running",
    createdAt: T0 - 20 * 60_000,
    completedAt: null,
    answer: null,
    tasks: [
      {
        taskId: "task-obj-1",
        parentTaskId: null,
        depth: 0,
        who: "Engineering Manager",
        role: "Manager",
        objective: "Add a contact page",
        state: "blocked",
        runtimeLabel: "Claude Code",
        model: "claude-sonnet-5",
        startedAt: T0 - 19 * 60_000,
        completedAt: null,
        summary: null,
      },
      {
        taskId: "task-sup",
        parentTaskId: "task-obj-1",
        depth: 1,
        who: "Website Supervisor",
        role: "Supervisor",
        objective: "Build the contact page on the objective's branch",
        state: "blocked",
        runtimeLabel: "Claude Code",
        model: null,
        startedAt: T0 - 18 * 60_000,
        completedAt: null,
        summary: null,
      },
      {
        taskId: "task-dev",
        parentTaskId: "task-sup",
        depth: 2,
        who: "Senior Developer",
        role: "Senior Developer",
        objective: "Write src/contact.html and commit it",
        state: "succeeded",
        runtimeLabel: "Codex",
        model: "gpt-5.5",
        startedAt: T0 - 17 * 60_000,
        completedAt: T0 - 12 * 60_000,
        summary: "Added the contact page and its form.",
      },
      {
        taskId: "task-review",
        parentTaskId: "task-sup",
        depth: 2,
        who: "Code Reviewer",
        role: "Code Reviewer",
        objective: "Review the contact page",
        state: "succeeded",
        runtimeLabel: "Claude Code",
        model: null,
        startedAt: T0 - 11 * 60_000,
        completedAt: T0 - 9 * 60_000,
        summary: "Changes requested: the form has no label.",
      },
      {
        taskId: "task-qa",
        parentTaskId: "task-sup",
        depth: 2,
        who: "QA Engineer",
        role: "QA Engineer",
        objective: "Run the tests",
        state: "awaitingApproval",
        runtimeLabel: "Claude Code",
        model: null,
        startedAt: T0 - 8 * 60_000,
        completedAt: null,
        summary: null,
      },
    ],
    workers: [
      {
        who: "Engineering Manager",
        role: "Manager",
        runtimeLabel: "Claude Code",
        model: "claude-sonnet-5",
        tasks: 1,
      },
      {
        who: "Senior Developer",
        role: "Senior Developer",
        runtimeLabel: "Codex",
        model: "gpt-5.5",
        tasks: 1,
      },
    ],
    files: [
      {
        path: "src/contact.html",
        added: 40,
        removed: 0,
        committed: true,
        branch: "plenipo/add-a-contact-page-corr0001",
      },
      {
        path: "src/styles.css",
        added: 3,
        removed: 1,
        committed: false,
        branch: "plenipo/add-a-contact-page-corr0001",
      },
    ],
    checks: [
      {
        taskId: "task-qa",
        who: "QA Engineer",
        command: "npm test",
        ok: true,
        test: true,
        at: T0 - 7 * 60_000,
      },
      {
        taskId: "task-qa",
        who: "QA Engineer",
        command: "npm run e2e",
        ok: false,
        test: true,
        at: T0 - 6 * 60_000,
      },
    ],
    branches: [
      {
        workspaceId: "ws-1",
        branch: "plenipo/add-a-contact-page-corr0001",
        baseRef: "main",
        commits: [{ hash: "def5678", subject: "Add the contact page" }],
        uncommitted: 1,
        pushed: true,
        path: "C:\\Users\\owner\\AppData\\Roaming\\Plenipo\\working-copies\\website-1",
        removed: false,
        mergeInto: null,
      },
    ],
    pullRequests: [
      {
        url: "https://github.com/northwind/website/pull/42",
        number: 42,
        taskId: "task-sup",
        who: "Website Supervisor",
      },
    ],
    reviews: [
      {
        taskId: "task-review",
        who: "Code Reviewer",
        verdict: "request-changes",
        findings: 1,
        at: T0 - 9 * 60_000,
      },
    ],
    findings: [
      {
        who: "Code Reviewer",
        severity: "major",
        file: "src/contact.html",
        summary: "The email field has no label",
        blocking: true,
        taskId: "task-review",
      },
    ],
    approvals: [
      {
        approvalId: "approval-1",
        taskId: "task-qa",
        who: "QA Engineer",
        summary: "Run npm run e2e",
        state: "waiting",
        requestedAt: T0 - 5 * 60_000,
      },
    ],
    blocked: [],
    problems: ["1 file changed but not committed on plenipo/add-a-contact-page-corr0001."],
    ...patch,
  };
}
