// What counts as a raw color (ADR-030 §3). Shared by scripts/check-colors.mjs (CSS) and
// eslint.config.js (TypeScript), so both refuse the same things.

/** Every CSS named color (CSS Color Module Level 4), except transparent and currentcolor. */
export const NAMED_COLORS = [
  "aliceblue",
  "antiquewhite",
  "aqua",
  "aquamarine",
  "azure",
  "beige",
  "bisque",
  "black",
  "blanchedalmond",
  "blue",
  "blueviolet",
  "brown",
  "burlywood",
  "cadetblue",
  "chartreuse",
  "chocolate",
  "coral",
  "cornflowerblue",
  "cornsilk",
  "crimson",
  "cyan",
  "darkblue",
  "darkcyan",
  "darkgoldenrod",
  "darkgray",
  "darkgreen",
  "darkgrey",
  "darkkhaki",
  "darkmagenta",
  "darkolivegreen",
  "darkorange",
  "darkorchid",
  "darkred",
  "darksalmon",
  "darkseagreen",
  "darkslateblue",
  "darkslategray",
  "darkslategrey",
  "darkturquoise",
  "darkviolet",
  "deeppink",
  "deepskyblue",
  "dimgray",
  "dimgrey",
  "dodgerblue",
  "firebrick",
  "floralwhite",
  "forestgreen",
  "fuchsia",
  "gainsboro",
  "ghostwhite",
  "gold",
  "goldenrod",
  "gray",
  "green",
  "greenyellow",
  "grey",
  "honeydew",
  "hotpink",
  "indianred",
  "indigo",
  "ivory",
  "khaki",
  "lavender",
  "lavenderblush",
  "lawngreen",
  "lemonchiffon",
  "lightblue",
  "lightcoral",
  "lightcyan",
  "lightgoldenrodyellow",
  "lightgray",
  "lightgreen",
  "lightgrey",
  "lightpink",
  "lightsalmon",
  "lightseagreen",
  "lightskyblue",
  "lightslategray",
  "lightslategrey",
  "lightsteelblue",
  "lightyellow",
  "lime",
  "limegreen",
  "linen",
  "magenta",
  "maroon",
  "mediumaquamarine",
  "mediumblue",
  "mediumorchid",
  "mediumpurple",
  "mediumseagreen",
  "mediumslateblue",
  "mediumspringgreen",
  "mediumturquoise",
  "mediumvioletred",
  "midnightblue",
  "mintcream",
  "mistyrose",
  "moccasin",
  "navajowhite",
  "navy",
  "oldlace",
  "olive",
  "olivedrab",
  "orange",
  "orangered",
  "orchid",
  "palegoldenrod",
  "palegreen",
  "paleturquoise",
  "palevioletred",
  "papayawhip",
  "peachpuff",
  "peru",
  "pink",
  "plum",
  "powderblue",
  "purple",
  "rebeccapurple",
  "red",
  "rosybrown",
  "royalblue",
  "saddlebrown",
  "salmon",
  "sandybrown",
  "seagreen",
  "seashell",
  "sienna",
  "silver",
  "skyblue",
  "slateblue",
  "slategray",
  "slategrey",
  "snow",
  "springgreen",
  "steelblue",
  "tan",
  "teal",
  "thistle",
  "tomato",
  "turquoise",
  "violet",
  "wheat",
  "white",
  "whitesmoke",
  "yellow",
  "yellowgreen",
];

const NAMED = NAMED_COLORS.join("|");

/** Color functions: rgb(), hsl(), and the newer ones (oklch(), lab(), color(), …). */
const FUNCTIONS = String.raw`\b(?:rgba?|hsla?|hwb|lab|lch|oklab|oklch|color)\s*\(`;

/** A hex color, or one URL-encoded (%23…) inside a data: image, which hides it from the rest. */
const HEX = String.raw`#[0-9a-fA-F]{3,8}\b|%23[0-9a-fA-F]{3,8}\b`;

/** Raw colors in a line of CSS: hex, color functions, and named colors used as a value. */
export function cssRawColors() {
  return new RegExp(
    String.raw`(${HEX})|${FUNCTIONS}|:\s*(?:[^;{}]*[\s,(])?(${NAMED})\s*(?=[;!})]|$)`,
    "gi",
  );
}

/** For ESLint selectors: hex and color functions anywhere in a string. */
export const TS_RAW = new RegExp(`${HEX}|${FUNCTIONS}`, "i");

/** For ESLint selectors: a named color as a whole value, or the last word of one ("1px solid red"). */
export const TS_NAMED = new RegExp(String.raw`(?:^|\s)(?:${NAMED})\s*(?:!important)?\s*$`, "i");

/** Style properties and SVG attributes whose value is a color. */
export const COLOR_KEYS = new RegExp(
  String.raw`^(?:color|background|backgroundColor|border(?:Top|Right|Bottom|Left)?(?:Color)?|outline(?:Color)?|fill|stroke|stopColor|floodColor|lightingColor|caretColor|accentColor|textDecorationColor|columnRuleColor|boxShadow|textShadow)$`,
);
